### ISSUE TITLE
postcssキメる

### ISSUE THREAD

**Issue by tosuke** [future-link/misskey-frontend#7]
autoprefixしようね

**Comment by otofune** [comment]
大きいメリットなのだが、実際のところどう？って感じのレベルなので決めていき

**Comment by rinsuki** [comment]
古いブラウザなんて窓から投げ捨ててしまえ

**Comment by tosuke** [comment]
autoprefixerをしたい(手作業でprefix付与するのはしんどいので)

**Comment by rinsuki** [comment]
そもそもCSSぐらいなら多少壊れても問題ないしCSSに関してはprefixなしでも良いのではと思う（まだchrome latestですらサポートしてないようなアレを使うのならアレだけど）

**Comment by otofune** [comment]
@petitsurume に同意です

**Comment by rokoucha** [comment]
@Petitsurume に同意で、動かん化石を使う人は居るのかといった気持ちです

**Comment by otofune** [comment]
必要な場面になったら使う
